@host = http://localhost:8787

GET {{host}}/auth


###
POST {{host}}/sign-in
Content-Type: application/json

{
    "username":"suraj",
    "password":"suraj1294"
}


###
GET {{host}}/auth/me
Authorization: Bearer test

###
GET {{host}}/users


###
POST {{host}}/users
Content-Type: application/json

{
    "name":"sagar",
    "email":"sagar@gmail.com",
    "role":"user"
}